[package]
name = "tetrad-client"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "tetrad_client_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tetrad-api-contract = { path = "../../../tetrad-api-contract" }
async-trait.workspace = true
torii-client = { git = "https://github.com/cmackenzie1/torii-rs", rev = "52d23111bf2b39dadbf02c4fe1b05ef9bf7b11d3", package = "torii-client" }
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
reqwest = { version = "0.13.4", features = ["json"] }


# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
