[package]
name = "tetrad-server"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
tetrad-api-contract = { path = "../../tetrad-api-contract" }
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
anyhow = "1.0"
axum = "0.8.9"
dotenvy = "0.15"
modql = { version = "0.5.0", features = ["with-sea-query"] }
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio-rustls", "macros", "migrate", "uuid"] }
sea-query = "1.0.0-rc.34"
sea-query-binder = { version = "0.8.0-rc.7", features = ["sqlx-sqlite"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
time = "0.3.55"
tracing-subscriber = { version = "0.3", features = ["env-filter", "std", "fmt"] }
tower-http = { version = "0.7.0", features = ["trace"] }
thiserror = "2.0.20"

[dev-dependencies]
axum-test = "21.1.0"
