[package]
name = "tetrad-server"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
tetrad-api-contract = { path = "../../tetrad-api-contract" }
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
anyhow = "1.0"
axum = "0.8.9"
dotenvy = "0.15"
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio-rustls", "macros", "migrate", "uuid"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
time = "0.3.55"
tracing-subscriber = { version = "0.3", features = ["env-filter", "std", "fmt"] }
tower-http = { version = "0.7.0", features = ["trace"] }
thiserror = "2.0.20"
torii = { git = "https://github.com/cmackenzie1/torii-rs", rev = "52d23111bf2b39dadbf02c4fe1b05ef9bf7b11d3", features = ["sqlite", "password"] }
torii-axum = { git = "https://github.com/cmackenzie1/torii-rs", rev = "52d23111bf2b39dadbf02c4fe1b05ef9bf7b11d3", features = ["password"] }
torii-storage-sqlite =  { git = "https://github.com/cmackenzie1/torii-rs", rev = "52d23111bf2b39dadbf02c4fe1b05ef9bf7b11d3" }

[dev-dependencies]
axum-test = "21.1.0"
