// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RegisterUserResponse = { torii_user_id: string, external_id: string, email: string, };
