// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegisterUserResponse } from "./RegisterUserResponse";

export type RegisterDto = { token: string, user: RegisterUserResponse, };
