name: tetrad-server CI

on:
  pull_request:
    # non tetrad-server paths are included as tetrad-server
    # uses these files
    paths:
      - "apps/tetrad-server/**"
      - "tetrad-api-contract/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "flake.nix"
      - ".github/workflows/tetrad-server-ci.yml"
  push:
    branches: [ main ]
    paths:
      - "apps/tetrad-server/**"
      - "tetrad-api-contract/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "flake.nix"
      - ".github/workflows/tetrad-server-ci.yml"
  workflow_dispatch:

jobs:
  nix-build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build server Nix package
        run: nix build .#server
        working-directory: ${{ github.workspace }}

  lint-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Check formatting
        run: nix develop .# -c cargo fmt --check

      - name: Clippy
        run: nix develop .# -c cargo clippy --workspace --exclude tetrad-client --all-targets --all-features -- -D warnings

  test-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Cargo tests
        run: nix develop .# -c cargo test --workspace --exclude tetrad-client --all-targets --no-fail-fast --
